ALTER TABLE vehicle_details
  ADD COLUMN IF NOT EXISTS drive_type VARCHAR(40),
  ADD COLUMN IF NOT EXISTS type_name VARCHAR(120),
  ADD COLUMN IF NOT EXISTS has_warranty BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS warranty_remaining VARCHAR(120),
  ADD COLUMN IF NOT EXISTS has_lpg BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS tramer_record VARCHAR(40),
  ADD COLUMN IF NOT EXISTS lien_pledge_status VARCHAR(40),
  ADD COLUMN IF NOT EXISTS plate_type VARCHAR(40),
  ADD COLUMN IF NOT EXISTS plate_number VARCHAR(20),
  ADD COLUMN IF NOT EXISTS chassis_last6 VARCHAR(6),
  ADD COLUMN IF NOT EXISTS legal_brand VARCHAR(100),
  ADD COLUMN IF NOT EXISTS commercial_name VARCHAR(120),
  ADD COLUMN IF NOT EXISTS legal_model_year SMALLINT;
