export const defaultCategories = [
  { id: 1, name: 'Araç', slug: 'arac', icon: '🚗', sub_categories: [] },
  { id: 2, name: 'Motor', slug: 'motor', icon: '🏍', sub_categories: [] },
  { id: 3, name: 'Emlak', slug: 'emlak', icon: '🏠', sub_categories: [] },
  { id: 4, name: 'Elektronik', slug: 'elektronik', icon: '📱', sub_categories: [] },
  { id: 5, name: 'Ev Eşyası', slug: 'ev-esyasi', icon: '🛋', sub_categories: [] },
  { id: 6, name: 'Giyim', slug: 'giyim', icon: '👕', sub_categories: [] },
  { id: 7, name: 'Hizmet', slug: 'hizmet', icon: '🔧', sub_categories: [] },
  { id: 8, name: 'İş İlanları', slug: 'is-ilanlari', icon: '💼', sub_categories: [] },
  { id: 9, name: 'Spor', slug: 'spor', icon: '⚽', sub_categories: [] },
  { id: 10, name: 'Diğer', slug: 'diger', icon: '📦', sub_categories: [] },
  { id: 11, name: 'Telefon', slug: 'telefon', icon: '📱', sub_categories: [] },
  { id: 12, name: 'Kişisel Bakım & Kozmetik', slug: 'kisisel-bakim-kozmetik', icon: '✨', sub_categories: [] },
  { id: 13, name: 'Anne & Bebek & Oyuncak', slug: 'anne-bebek-oyuncak', icon: '🧸', sub_categories: [] },
  { id: 14, name: 'Hobi & Kitap & Müzik', slug: 'hobi-kitap-muzik', icon: '🎸', sub_categories: [] },
  { id: 15, name: 'Ofis & Kırtasiye', slug: 'ofis-kirtasiye', icon: '🗂', sub_categories: [] },
  { id: 16, name: 'Spor & Outdoor', slug: 'spor-outdoor', icon: '🏕', sub_categories: [] },
  { id: 17, name: 'Diğer Araçlar', slug: 'diger-araclar', icon: '🚚', sub_categories: [] },
  { id: 18, name: 'Antika', slug: 'antika', icon: '🏺', sub_categories: [] },
  { id: 19, name: 'Pet Shop', slug: 'pet-shop', icon: '🐾', sub_categories: [] },
]
